name: PR Checks

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Run Test
      run: echo "Test Passed"

    - name: Lint Check
      run: echo "Lint Passed"
